on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test
jobs:
  test:
    timeout-minutes: 61
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go version
        go test -timeout 1h ./...

  test-gotip:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      env:
        GO_COMMIT: e50f0f372b07149e9cf16b8fec80d2d72efe2a87 # 2022-02-11
      run: |
        cd $HOME
        mkdir $HOME/gotip
        cd $HOME/gotip

        wget -O gotip.tar.gz https://go.googlesource.com/go/+archive/${GO_COMMIT}.tar.gz
        tar -xf gotip.tar.gz
        echo "devel go1.18-${GO_COMMIT}" >VERSION

        cd src
        # GOGC=off helps Go build about 20% faster, if we can spare memory.
        GOGC=off ./make.bash
        echo "GOROOT=$HOME/gotip" >>$GITHUB_ENV
        echo "$HOME/gotip/bin" >>$GITHUB_PATH
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go version
        go test -timeout 1h ./...

  code-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test that only LF line endings are used
      run: ./scripts/crlf-test.sh
