on:
  push:
    branches:
      - master
      - ci-test
  pull_request:
    branches:
      - master

name: Test
jobs:
  test:
    timeout-minutes: 61
    strategy:
      matrix:
        go-version: [1.19.x]
        # TODO: revert to macos-latest once we figure out https://github.com/burrowers/garble/issues/609.
        os: [ubuntu-latest, macos-11, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - name: Test
      run: |
        go version
        go test -timeout 1h ./...

  test-gotip:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      env:
        GO_COMMIT: cb07765045aed5104a3df31507564ac99e6ddce8 # 2022-12-13
      run: |
        cd $HOME
        mkdir $HOME/gotip
        cd $HOME/gotip

        wget -O gotip.tar.gz https://go.googlesource.com/go/+archive/${GO_COMMIT}.tar.gz
        tar -xf gotip.tar.gz
        echo "devel go1.20-${GO_COMMIT}" >VERSION

        cd src
        ./make.bash
        echo "GOROOT=$HOME/gotip" >>$GITHUB_ENV
        echo "$HOME/gotip/bin" >>$GITHUB_PATH
    - uses: actions/checkout@v3
    - name: Test
      run: |
        go version
        go test -timeout 1h ./...

  script-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./scripts/crlf-test.sh
